# Generated by Django 3.0.3 on 2020-04-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200414_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avg_rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
